/****************
 * This code was automatically generated by lwm2m_codegen.
 ****************/
package org.eclipse.leshan.client.demo;

import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Random;
import java.util.List;
import java.util.Arrays;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.Scanner;

import org.eclipse.leshan.client.servers.ServerIdentity;
import org.eclipse.leshan.client.resource.BaseInstanceEnabler;
import org.eclipse.leshan.core.model.ResourceModel.Type;
import org.eclipse.leshan.core.model.ObjectModel;
import org.eclipse.leshan.core.node.LwM2mResource;
import org.eclipse.leshan.core.request.argument.Arguments;
import org.eclipse.leshan.core.response.ExecuteResponse;
import org.eclipse.leshan.core.response.ReadResponse;
import org.eclipse.leshan.core.response.WriteResponse;
import org.eclipse.leshan.core.util.NamedThreadFactory;


import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JFrame;
import javax.swing.JComboBox;
import javax.swing.WindowConstants;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Container;
import java.awt.GridLayout;
import java.awt.EventQueue;

public class Luminaire extends BaseInstanceEnabler {
    static final int OBJECT_ID_LUMINAIRE = 33001;
    static final int OBJECT_ID = 33001;
    // Static values for resource items
    private static final int RES_POWER = 30000;
    private static final int RES_TYPE = 30002;
    private static final int RES_PEAK_POWER = 30003;
    private static final int RES_DIM_LEVEL = 30004;
    private static final List<Integer> supportedResources =
     Arrays.asList(
             RES_POWER
           , RES_TYPE
           , RES_PEAK_POWER
           , RES_DIM_LEVEL
           );
    // Variables storing current values.

    private boolean vPower = false;

    // LED, Halogen
    private String vType = "";

    private long vPeakPower = 0;

    // 0..100
    private long vDimLevel = 0;

    // Sense HAT lamp process (null when not running on a Pi with the script).
    private Process senseHatProcess;
    private BufferedWriter senseHatWriter;

    public Luminaire() {
        // 2IMN15: Start Sense HAT LED controller if the helper script is present.
        startSenseHatLamp();

        // Ensure the background process is cleaned up on JVM exit.
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            if (senseHatProcess != null) {
                try {
                    if (senseHatWriter != null) senseHatWriter.close();
                } catch (IOException ignored) {}
                senseHatProcess.destroy();
            }
        }, "luminaire-shutdown"));
    }

    // -----------------------------------------------------------------------
    // Sense HAT LED helpers
    // -----------------------------------------------------------------------

    /**
     * Try to start the Sense HAT Python helper script.
     * Looks for "sensehat_lamp.py" in the current working directory.
     * Logs a warning and falls back silently when the script is absent or the
     * sense_hat library is not installed (non-Pi platforms).
     */
    private void startSenseHatLamp() {
        File script = new File("sensehat_lamp.py");
        if (!script.exists()) {
            System.out.println("[Luminaire] sensehat_lamp.py not found – LED matrix output disabled.");
            return;
        }
        try {
            ProcessBuilder pb = new ProcessBuilder("python3", script.getAbsolutePath());
            pb.redirectErrorStream(true);  // merge stderr into stdout to avoid buffer fill
            senseHatProcess = pb.start();

            final java.io.InputStream lampOut = senseHatProcess.getInputStream();

            // Read the first line (expect "READY") with a short timeout.
            java.util.concurrent.ExecutorService exec =
                    java.util.concurrent.Executors.newSingleThreadExecutor();
            java.util.concurrent.Future<String> firstLine = exec.submit(
                    () -> new java.io.BufferedReader(new java.io.InputStreamReader(lampOut)).readLine());
            exec.shutdown();

            String ready;
            try {
                ready = firstLine.get(3, java.util.concurrent.TimeUnit.SECONDS);
            } catch (Exception e) {
                firstLine.cancel(true);
                exec.shutdownNow();
                senseHatProcess.destroy();
                senseHatProcess = null;
                System.err.println("[Luminaire] Sense HAT script did not become ready: " + e.getMessage());
                return;
            }

            if (!"READY".equals(ready)) {
                senseHatProcess.destroy();
                senseHatProcess = null;
                System.err.println("[Luminaire] Sense HAT script sent unexpected first line: " + ready);
                return;
            }

            // Drain remaining stdout in background to prevent pipe buffer blockage.
            Thread drainer = new Thread(() -> {
                byte[] buf = new byte[512];
                try { while (lampOut.read(buf) != -1) {} } catch (IOException ignored) {}
            }, "lamp-stdout-drainer");
            drainer.setDaemon(true);
            drainer.start();

            if (!"READY".equals(ready)) {
                senseHatProcess.destroy();
                senseHatProcess = null;
                System.err.println("[Luminaire] Sense HAT script sent unexpected first line: " + ready);
                return;
            }

            senseHatWriter = new BufferedWriter(
                    new OutputStreamWriter(senseHatProcess.getOutputStream()));
            System.out.println("[Luminaire] Sense HAT LED matrix active.");

        } catch (IOException e) {
            System.err.println("[Luminaire] Could not start sensehat_lamp.py: " + e.getMessage());
            if (senseHatProcess != null) {
                senseHatProcess.destroy();
                senseHatProcess = null;
            }
        }
    }

    /**
     * Send a command to the Sense HAT lamp script.
     * Commands: "off", "on <dim>" where dim is 0-100.
     * Silently ignored when the script is not running.
     */
    private void sendLampCommand(String command) {
        if (senseHatWriter == null) return;
        try {
            senseHatWriter.write(command);
            senseHatWriter.newLine();
            senseHatWriter.flush();
        } catch (IOException e) {
            System.err.println("[Luminaire] Failed to send lamp command: " + e.getMessage());
            senseHatWriter = null;
        }
    }

    @Override
    public synchronized ReadResponse read(ServerIdentity identity, int resourceId) {
	switch (resourceId) {
	case RES_POWER:
	    return ReadResponse.success(resourceId, vPower);
	case RES_TYPE:
	    return ReadResponse.success(resourceId, vType);
	case RES_PEAK_POWER:
	    return ReadResponse.success(resourceId, vPeakPower);
	case RES_DIM_LEVEL:
	    return ReadResponse.success(resourceId, vDimLevel);
	default:
	    return super.read(identity, resourceId);
	}
    }
    
    @Override
    public WriteResponse write(ServerIdentity identity, boolean replace, int resourceId, LwM2mResource value) {
	switch (resourceId) {
	case RES_POWER:
	    // vPower = (Boolean) value.getValue();
	    // fireResourceChange(resourceId);
	    setPower((Boolean) value.getValue());
	    return WriteResponse.success();
	case RES_DIM_LEVEL:
	    // vDimLevel = (Integer) value.getValue();
	    // fireResourceChange(resourceId);
	    setDimLevel((Long) value.getValue());
	    return WriteResponse.success();
	default:
	    return super.write(identity, replace, resourceId,value);
	}
    }
    
    @Override
    public synchronized ExecuteResponse execute(ServerIdentity identity, int resourceId, Arguments arguments) {
	switch (resourceId) {
	default:
	    return super.execute(identity, resourceId,arguments);
	}
    }
    
    @Override
    public List<Integer> getAvailableResourceIds(ObjectModel model) {
	return supportedResources;
    }
    
    // Configure before registration, don't fire.
    public void configure(String lumtype, long peakpower) {
	vType = lumtype;
	vPeakPower = peakpower;
    }
    
    private synchronized void setPower(boolean value) {
	if (vPower != value) {
	    vPower = value;
	    // 2IMN15: Update Sense HAT LED matrix to reflect new power state.
	    if (vPower) {
		sendLampCommand("on " + vDimLevel);
	    } else {
		sendLampCommand("off");
	    }
	    fireResourceChange(RES_POWER);
	}
    }
    
    private synchronized void setType(String value) {
	if (vType != value) {
	    vType = value;
	    fireResourceChange(RES_TYPE);
	}
    }

    private synchronized void setPeakPower(long value) {
	if (vPeakPower != value) {
	    vPeakPower = value;
	    fireResourceChange(RES_PEAK_POWER);
	}
    }

    private synchronized void setDimLevel(long value) {
	if (vDimLevel != value) {
	    vDimLevel = value;
	    // 2IMN15: Update Sense HAT LED matrix to reflect new dim level (only if powered on).
	    if (vPower) {
		sendLampCommand("on " + vDimLevel);
	    }
	    fireResourceChange(RES_DIM_LEVEL);
	}
    }

}
