/****************
 * This code was automatically generated by lwm2m_codegen.
 ****************/
package org.eclipse.leshan.client.demo;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;
import java.util.Scanner;

import org.eclipse.leshan.client.servers.ServerIdentity;
import org.eclipse.leshan.client.resource.BaseInstanceEnabler;
import org.eclipse.leshan.core.model.ResourceModel.Type;
import org.eclipse.leshan.core.model.ObjectModel;
import org.eclipse.leshan.core.node.LwM2mResource;
import org.eclipse.leshan.core.request.argument.Arguments;
import org.eclipse.leshan.core.response.ExecuteResponse;
import org.eclipse.leshan.core.response.ReadResponse;
import org.eclipse.leshan.core.response.WriteResponse;
import org.eclipse.leshan.core.util.NamedThreadFactory;

//
// Some classes for creating a GUI.
//
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JFrame;
import javax.swing.JComboBox;
import javax.swing.WindowConstants;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Container;
import java.awt.GridLayout;
import java.awt.EventQueue;

public class PresenceDetector extends BaseInstanceEnabler {
    static final int OBJECT_ID_PRESENCE_DETECTOR = 33000;
    static final int OBJECT_ID = 33000;
    // Static values for resource items
    private static final int RES_POWER = 30000;
    private static final int RES_PRESENCE = 30001;
    private static final List<Integer> supportedResources =
     Arrays.asList(
             RES_POWER
           , RES_PRESENCE
           );
    // Variables storing current values.

    private boolean vPower = false;
    private boolean vPresence = false;

    // State for the input interface (Sense HAT, GUI, or timed fallback).
    private volatile boolean running = true;
    private Process senseHatProcess;
    private Thread inputThread;
    private ScheduledExecutorService timedToggleScheduler;
    // GUI label updated to reflect the current presence value.
    private JLabel presenceValueLabel;

    public PresenceDetector() {
        // 2IMN15: Determine which input interface to use:
        //   1. Sense HAT joystick (Raspberry Pi with sensehat_joystick.py nearby)
        //   2. Swing GUI toggle button (non-headless desktop platforms)
        //   3. Timed auto-toggle (headless / CI fallback)
        if (!startSenseHat()) {
            if (!java.awt.GraphicsEnvironment.isHeadless()) {
                startGuiToggle();
            } else {
                startTimedToggle();
            }
        }

        // Ensure the background process/thread is cleaned up on JVM exit.
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            running = false;
            if (timedToggleScheduler != null) {
                timedToggleScheduler.shutdownNow();
            }
            if (senseHatProcess != null) {
                senseHatProcess.destroy();
            }
            if (inputThread != null) {
                inputThread.interrupt();
            }
        }, "presence-shutdown"));
    }

    // -----------------------------------------------------------------------
    // Input interface helpers
    // -----------------------------------------------------------------------

    /**
     * Try to start the Sense HAT Python helper script.
     * Looks for "sensehat_joystick.py" in the current working directory.
     * Returns true if the script started successfully and printed "READY".
     */
    private boolean startSenseHat() {
        File script = new File("sensehat_joystick.py");
        if (!script.exists()) {
            return false;
        }
        try {
            ProcessBuilder pb = new ProcessBuilder("python3", script.getAbsolutePath());
            pb.redirectErrorStream(false);
            senseHatProcess = pb.start();

            final BufferedReader reader = new BufferedReader(
                    new InputStreamReader(senseHatProcess.getInputStream()));

            // Wait up to 3 seconds for the READY signal.
            ExecutorService exec = Executors.newSingleThreadExecutor();
            Future<String> firstLine = exec.submit(reader::readLine);
            exec.shutdown();

            String ready;
            try {
                ready = firstLine.get(3, TimeUnit.SECONDS);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                firstLine.cancel(true);
                senseHatProcess.destroy();
                senseHatProcess = null;
                return false;
            } catch (TimeoutException | ExecutionException e) {
                firstLine.cancel(true);
                senseHatProcess.destroy();
                senseHatProcess = null;
                return false;
            }

            if (!"READY".equals(ready)) {
                senseHatProcess.destroy();
                senseHatProcess = null;
                return false;
            }

            // Background thread: read PRESS events from the Python script.
            // The shutdown hook sets running=false and destroys the process to
            // unblock any blocking readLine(), allowing this thread to exit cleanly.
            inputThread = new Thread(() -> {
                try {
                    String line;
                    while (running && (line = reader.readLine()) != null) {
                        if ("PRESS".equals(line.trim())) {
                            togglePresence();
                        }
                    }
                } catch (IOException e) {
                    if (running) {
                        System.err.println("[PresenceDetector] Sense HAT reader ended: " + e.getMessage());
                    }
                }
            }, "sensehat-reader");
            inputThread.start();

            System.out.println("[PresenceDetector] Sense HAT joystick active."
                    + " Press the middle (centre) button to toggle presence.");
            return true;

        } catch (IOException e) {
            System.err.println("[PresenceDetector] Could not start sensehat_joystick.py: " + e.getMessage());
            if (senseHatProcess != null) {
                senseHatProcess.destroy();
                senseHatProcess = null;
            }
            return false;
        }
    }

    /**
     * Create a minimal Swing GUI with a "Toggle Presence" button.
     * Used on desktop platforms (Mac, Windows, Linux with display).
     */
    private void startGuiToggle() {
        presenceValueLabel = new JLabel("ABSENT");
        JButton toggleButton = new JButton("Toggle Presence");
        toggleButton.addActionListener(e -> togglePresence());

        JFrame guiFrame = new JFrame("Presence Detector");
        guiFrame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        guiFrame.getContentPane().setLayout(new GridLayout(1, 2, 10, 10));
        guiFrame.getContentPane().add(toggleButton);
        guiFrame.getContentPane().add(presenceValueLabel);
        guiFrame.pack();
        guiFrame.setSize(300, 80);

        EventQueue.invokeLater(() -> guiFrame.setVisible(true));
        System.out.println("[PresenceDetector] GUI toggle active. Use the button to toggle presence.");
    }

    /**
     * Fallback for headless environments: automatically toggle presence every
     * 10 seconds so the LwM2M scenario can be observed without interaction.
     */
    private void startTimedToggle() {
        timedToggleScheduler = Executors.newSingleThreadScheduledExecutor(
                new NamedThreadFactory("presence-toggle"));
        timedToggleScheduler.scheduleAtFixedRate(this::togglePresence, 5, 10, TimeUnit.SECONDS);
        System.out.println("[PresenceDetector] Timed toggle active (auto-toggles every 10 s).");
    }

    /** Toggle the presence boolean and notify LwM2M observers. */
    private synchronized void togglePresence() {
        setPresence(!vPresence);
        System.out.println("[PresenceDetector] Presence toggled to: " + vPresence);
        if (presenceValueLabel != null) {
            final String text = vPresence ? "PRESENT" : "ABSENT";
            EventQueue.invokeLater(() -> presenceValueLabel.setText(text));
        }
    }

    @Override
    public synchronized ReadResponse read(ServerIdentity identity, int resourceId) {
	switch (resourceId) {
	case RES_POWER:
	    return ReadResponse.success(resourceId, vPower);
	case RES_PRESENCE:
	    return ReadResponse.success(resourceId, vPresence);
	default:
	    return super.read(identity, resourceId);
	}
    }
    
    @Override
    public WriteResponse write(ServerIdentity identity, boolean replace, int resourceId, LwM2mResource value) {
	switch (resourceId) {
	case RES_POWER:
	    // vPower = (Boolean) value.getValue();
	    // fireResourceChange(resourceId);
	    setPower((Boolean) value.getValue());
	    return WriteResponse.success();
	default:
	    return super.write(identity, replace, resourceId,value);
	}
    }

    @Override
    public synchronized ExecuteResponse execute(ServerIdentity identity, int resourceId, Arguments arguments) {
	switch (resourceId) {
	default:
	    return super.execute(identity, resourceId,arguments);
	}
    }
    
    @Override
    public List<Integer> getAvailableResourceIds(ObjectModel model) {
	return supportedResources;
    }

    private synchronized void setPower(boolean value) {
	if (vPower != value) {
	    vPower = value;
	    fireResourceChange(RES_POWER);
	}
    }
    
    private synchronized void setPresence(boolean value) {
	if (vPresence != value) {
	    vPresence = value;
	    fireResourceChange(RES_PRESENCE);
	}
    }
    
}
